### ISSUE TITLE
Terraform destroy returning error 

### ISSUE THREAD

**Issue by SaumyaBhushan** [XtratusCloud/terraform-provider-azureipam#4] opened 2023-07-11 06:14 UTC
**Describe the bug**
After running terraform apply successfully for azure ipam reservation resource . I want to destroy the resources , while running terraform destroy it is returning error body 204 .

**To Reproduce**
Run following commands 
- terraform init
- terraform plan 
- terraform apply --auto-approve
- terraform destroy --auto-approve

Terraform destroy step will produce the error

**Expected behavior**

terraform destroy should remove the reservation without any error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. linux ubuntu, windows]
 - Browser and version edge
 - Terraform version 
 - Other relevant providers

**Additional context**

**Comment by XtratusCloud** [comment] 2023-08-04 10:20
sorry for the delay 
I will try to reproduce the error
please, could you provide me with some additional information?:
- version of azureipam used (or commit in the azureipam repository used for deployment)
- the error message it shows you after destroy command.
-

**Comment by XtratusCloud** [comment] 2023-08-07 06:59
I have performed several apply and destroy tests and I cannot reproduce the error.
We would need more information about your running environment (operating system, terraform version, etc) and the IPAM version you have installed (commit number or date) in order to perform specific tests.  

we look forward to hearing from you

**Comment by XtratusCloud** [comment] 2023-09-12 08:37
We have not been able to reproduce the described error in a test scenario, and you have not provided any further information about the context of your test or the specific error message. 

We proceed to close the issue. 
Thank you,

**Closed by XtratusCloud** 2023-09-12 08:37 UTC
